application/models/task_types.py
from ..db import db

class TaskType(db.Model):
    __tablename__ = "task_types"
    
    id = db.Column(
        db.Integer,
        primary_key=True,
        autoincrement=True
    )
    name = db.Column(
        db.String(100),
        nullable=False
    )
    tasks = db.relationship(
        'Task', 
        backref='task_type', 
        lazy='joined'
    )

application/models/tasks.py
from ..db import db

class Task(db.Model):
    __tablename__ = "tasks"
    
    id = db.Column(
        db.Integer,
        primary_key=True,
        autoincrement=True
    )
    task_type_id = db.Column(
        db.Integer,
        db.ForeignKey('task_types.id'),
        nullable=False
    )
    user_id = db.Column(
        db.Integer,
        db.ForeignKey('users.id')
    )
    title = db.Column(
        db.String(100),
        nullable=False
    )
    content = db.Column(
        db.Text,
        nullable=False
    )
    priority = db.Column(
        db.String(100),
        nullable=False,
        server_default="LOW"
    )
    completed = db.Column(
        db.Boolean,
        server_default="0"
    )
    date_created  = db.Column(
        db.DateTime,  
        default=db.func.current_timestamp()
    )
    date_modified = db.Column(
        db.DateTime,  
        default=db.func.current_timestamp(),
        onupdate=db.func.current_timestamp()
    )
    

application/models/users.py
from ..db import db
from flask_login import UserMixin

class User(UserMixin, db.Model):
    __tablename__ = "users"
    
    id = db.Column(
        db.Integer,
        primary_key=True,
        autoincrement=True,
    )
    email = db.Column(
        db.String(255),
        unique=True,
        nullable=False
    )
    first_name = db.Column(
        db.String(255),
        nullable=False
    )
    last_name = db.Column(
        db.String(255),
        nullable=False
    )
    password = db.Column(
        db.String(100)
    )
    tasks = db.relationship(
        'Task', 
        backref='user', 
        lazy='joined'
    )

application/__init__.py
import os
from flask import Flask
from flask_login import LoginManager
from application._helpers import load_config
from application.momentjs import momentjs

def create_app():
    app = Flask(__name__, template_folder='./templates')
    mode = app.env
    Config = load_config(mode)
    app.config.from_object(Config)
    
    app.add_template_global(name='momentjs', f=momentjs)
    
    from .db import db
    db.init_app(app)
    
    login_manager = LoginManager()
    login_manager.login_view = 'nonAuth.login'
    login_manager.init_app(app)
    
    from .models.users import User
    from .models.task_types import TaskType
    from .models.tasks import Task
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))
    
    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass
    
    with app.app_context():
        # import non auth routes
        from .non_auth_routes.non_auth import nonAuth as non_auth_blueprint
        app.register_blueprint(non_auth_blueprint)
        
        # import auth routes
        from .auth_routes.auth import auth as auth_blueprint
        app.register_blueprint(auth_blueprint)
        
        db.create_all()
        
        return app
    

application/auth_routes/__init__.py
# application/auth_routes/__init__.py

application/auth_routes/auth.py
from flask import render_template, Blueprint, redirect, url_for, request, flash
from flask_login import login_required, logout_user
from werkzeug.exceptions import abort
from application.models import *
from application.db import session

auth = Blueprint('auth', __name__)
TaskType = task_types.TaskType
Task = tasks.Task

def get_task_type(name):
    task_type = TaskType.query.filter_by(name=name).first()
    return task_type

def get_task_types():
    task_types = TaskType.query.all()
    return task_types


@auth.route('/')
@login_required
def index():
    taskTypes = get_task_types()

    tasks = session.query(TaskType).join(Task, Task.task_type_id == Task.id).all()

    return render_template('index.html', types=tasks)

    
@auth.route('/todos-detail/<name>', methods=['GET', 'POST'])
@login_required
def taskDetails(name):
    taskType = get_task_type(name)
    
    tasks = Task.query.filter_by(task_type_id = taskType.id).all()
    
    return render_template('todo-detail.html', tasks=tasks)


@auth.route('/create-type', methods=['POST',])
@login_required
def createType():
    if request.method == 'POST':
        name = request.form['name']
        
        existing_type = TaskType.query.filter_by(name=name).first()
        
        
        if existing_type:
            flash('Group already exists!')
            return redirect(url_for('auth.index'))

        new_type = TaskType(
            name = name
        )
        session.add(new_type)
        session.commit()
        
        return redirect(url_for('auth.index'))
    

@auth.route('/create-task', methods=['POST',])
@login_required
def createTask():
    if request.method == 'POST':
        taskTypeId = request.form['taskTypeId']
        title = request.form['title']
        content = request.form['content']
        priority = request.form['priority']
        
        if not taskTypeId:
            flash('Please select a task type')
        elif not title:
            flash('Please input a title for the task')
        else:
            task = Task(
                task_type_id = taskTypeId,
                title = title,
                content = content,
                priority = priority
            )
            
            session.add(task)
            session.commit()
            
            return redirect(url_for('auth.index'))

    
@auth.route('/check-complete/<int:id>', methods=['POST',])
@login_required
def checkComplete(id):
    if request.method == 'POST':
        completed = 'check' in request.form

        if completed == True:
            checked = 1
        else:
            checked = 0
        
        session.query(Task).filter(Task.id == id).update({Task.completed: checked}, synchronize_session = False)
        session.commit()
        
        return redirect(url_for('auth.index'))
    

@auth.route('/delete-task/<int:id>', methods=['POST',])
@login_required
def deleteTask(id):
    taskType = request.form['grpName']
    
    Task.query.filter_by(id=id).delete()
    flash('Task Deleted Sucessfully')
    
    return redirect(url_for('taskDetails', name=taskType))
   
 
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('nonAuth.login'))

application/non_auth_routes/__init__.py
# application/non_auth_routes/__init__.py

application/templates/app-nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <!-- <button>Back</button> -->
    <a href="{{ url_for('auth.index') }}" style="z-index: 999;">
        <span class="badge badge-info">Back</span>
    </a>
    <div class="app-nav collapse navbar-collapse" id="navbarSupportedContent" style="position: absolute;
        margin: auto;
        right: 0;
        left: 0;
        justify-content: center";
    >
        <ul class="navbar-nav">
            <li class="nav-item">
                <button
                class="btn btn-secondary btn-sm"
                onClick={this.openNewListForm}
                style="display:grid; color:#495057; background-color:transparent; border:none;"
                >
                   {{ request.path.split('/')[-1] }}
                    <span style="font-size:0.7em;">On this computer</span>
                </button>
            </li>
        </ul>
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <!-- <li class="nav-item">
                <a class="btn btn-light mr-2 btn-sm" href="#">
                    <i class="fa fa-list"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="btn btn-light mr-2 btn-sm" href="#">
                    <i class="fa fa-check"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="btn btn-light mr-2 btn-sm" href="#">
                    <i class="fa fa-search"></i>
                </a>
            </li> -->
            <li class="nav-item">
                <a class="btn btn-light mr-2 btn-sm" href="{{ url_for('auth.logout') }}">
                    <i class="fa fa-eject"></i>
                </a>
            </li>
        </ul>
    </div>
</nav>

application/templates/home-nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a href="#" 
                    data-toggle="modal" 
                    data-target="#newTask"
                >
                    <span class="badge badge-warning">New Task</span>
                </a>
            </li>
        {% endif %}
        </ul>
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
                <!-- <li class="nav-item">
                    <a class="btn btn-light mr-2 btn-sm" href="#">
                        <i class="fa fa-list"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-light mr-2 btn-sm" href="#">
                        <i class="fa fa-check"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-light mr-2 btn-sm" href="#">
                        <i class="fa fa-search"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-light mr-2 btn-sm" href="#">
                        <i class="fa fa-hamburger"></i>
                    </a>
                </li> -->
                <li class="nav-item">
                    <a class="btn btn-light mr-2 btn-sm" href="{{ url_for('auth.logout') }}">
                        <i class="fa fa-eject"></i>
                    </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a href="{{ url_for('nonAuth.signup') }}" class="navbar-item">
                        Sign Up
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

application/templates/index.html
    {% extends 'layout.html' %}
    {% block content %}
        <hr class="m-2" />
        <!-- cards containing items -->
        <div class="card-deck">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="notification is-danger">
                        {{ messages[0] }}
                    </div>
                {% endif %}
            {% endwith %}
            {% if types %}
                {% for type in types %}
                    <div class="card">
                        <div class="card-body">
                            <ul>
                                {% for item in type.tasks %}
                                <li class=item-cards>
                                    <div class="col-sm-8 {% if item.completed == 1 %} task-completed {% endif %}">
                                        <div class="row">
                                            <div class="col-sm-1">
                                                <form action="{{ url_for('auth.checkComplete', id=item.id) }}" method="post">
                                                    <input 
                                                        id="task-{{item.id}}" 
                                                        class="check-task-button" 
                                                        type="checkbox" 
                                                        name="check" {% if item.completed == 1 %} CHECKED {% endif %} onChange="this.form.submit()"
                                                    />
                                                </form>
                                            </div>
                                            <div class="col-sm-8">
                                                <label class="label" for="task-{{item.id}}">{{ item.title }}</label>
                                            </div>
                                        </div>
                                    </div>
                                    <span>
                                        @ {{ momentjs(item.date_created).fromNow() }}
                                    </span>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <a href="{{ url_for('auth.taskDetails', name=type.name) }}">
                            <div class="card-footer">
                                <strong>{{ type.name }}</strong>
                                <p class="m-0 text-muted">
                                <small>On this computer</small>
                                </p>
                            </div>
                        </a>  
                    </div>
                {% endfor %}
            {% else %}
                <div class="card">
                    <div class="card-body">
                        <h6>No Tasks</h6>
                        <span>
                            <a href="#" 
                                data-toggle="modal" 
                                data-target="#newGroup"
                            >
                                <span class="badge badge-info">Create Task Group</span>
                            </a>
                        </span> or 
                        <span>Click New Task to create a Task</span>
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="modal fade" id="newGroup" tabindex="-1" role="dialog" aria-labelledby="groupTask" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title" id="groupTask">Create Task Group</h4>
                    </div>
                    <div class="modal-body">
                        <form action="{{ url_for('auth.createType') }}" class="form-inline" method="post">
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input name="name" class="form-control" type="text" value="{{ request.form['name'] }}"/>
                            </div>
                            <button id="createType" type="submit" class="btn btn-primary">
                                Create Group
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="newTask" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel">Create New Task</h4>
                    </div>
                    <div class="modal-body">
                        <form action="{{ url_for('auth.createTask') }}" class="form-inline" method="post">
                            <div class="form-group">
                                <label>Select Type of Task</label>
                                <select class="form-control" id="slct" name=taskTypeId>
                                    {% if types is not none %}
                                        {% for type in types %}
                                            <option value="{{type.id}}">
                                                {{ type['name'] }}
                                            </option>
                                        {% endfor %}
                                    {% else %}
                                        <option>-No Value-</option>
                                    {% endif %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="inputNotes">Title</label>
                                <input name="title" class="form-control" type="text" value="{{ request.form['title'] }}"/>
                            </div>
                            <div class="form-group">
                                <label for="inputNotes">Notes</label>
                                <textarea name="content" class="form-control">{{ request.form['content'] }}</textarea>
                            </div>
                            <div class="form-row">
                                <div class="form-group">
                                    <label for="inputState">Priority</label>
                                    <select id="inputState" class="form-control" name="priority">
                                        <option value="HIGH">High</option>
                                        <option value="LOW">Low</option>
                                    </select>
                                </div>
                            </div>
                            <button id="createTask" type="submit" class="btn btn-primary">
                                Create Task
                            </button>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    {% endblock content %}

application/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename= 'css/style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />

    <link href="https://fonts.googleapis.com/css?family=Livvic|Montserrat|Philosopher|ZCOOL+XiaoWei|Srisakdi:700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.materialdesignicons.com/5.0.45/css/materialdesignicons.min.css" rel="stylesheet">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.0/moment-with-locales.min.js" integrity="sha512-EATaemfsDRVs6gs1pHbvhc6+rKFGv8+w4Wnxk4LmkC0fzdVoyWb+Xtexfrszd1YuUMBEhucNuorkf8LpFBhj6w==" crossorigin="anonymous"></script>

    {% if title %}
        <title>Todo List - {{ title }}</title>
    {% else %}
        <title>Todo List</title>
    {% endif %}
</head>
<body>
    {% if url_for('auth.taskDetails', name=request.path.split('/')[-1]) == request.path %}
        {% include "app-nav.html" %}
    {% else %}
        {% include "home-nav.html" %}
    {% endif %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

application/templates/login.html
{% extends "layout.html" %}

{% block content %}
    <div class="column is-4 is-offset-4">
        <h3 class="title">Login</h3>
        <div class="box">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="notification is-danger">
                    {{ messages[0] }}
                </div>
            {% endif %}
            {% endwith %}
            <form method="POST" action="{{ url_for('nonAuth.login') }}">
                <div class="field">
                    <div class="control">
                        <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        <input class="input is-large" type="password" name="password" placeholder="Your Password">
                    </div>
                </div>
                <div class="field">
                    <label class="checkbox">
                        <input type="checkbox">
                        Remember me
                    </label>
                </div>
                <button class="button is-block is-info is-large is-fullwidth">Login</button>
            </form>
        </div>
    </div>
{% endblock %}

application/templates/signup.html
{% extends "layout.html" %}

{% block content %}
    <div class="column is-4 is-offset-4">
        <h3 class="title">Sign Up</h3>
        <div class="box">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="notification is-danger">
                    {{ messages[0] }}. Go to <a href="{{ url_for('nonAuth.login') }}">login page</a>.
                </div>
            {% endif %}
            {% endwith %}
            <form method="POST" action="{{ url_for('nonAuth.signup') }}">
                <div class="field">
                    <div class="control">
                        <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <input class="input is-large" type="text" name="first_name" placeholder="First Name" autofocus="">
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <input class="input is-large" type="text" name="last_name" placeholder="Last Name" autofocus="">
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <input class="input is-large" type="password" name="password" placeholder="Password">
                    </div>
                </div>

                <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
            </form>
        </div>
    </div>
{% endblock %}

application/templates/todo-detail.html
    {% extends 'layout.html' %}
    {% block content %}
        <div class="accordion vertical">
            <ul>
                {% for task in tasks %}
                    <li class="card {% if task.completed == 1 %} task-completed {% endif %}">
                        <input 
                            class="box" 
                            type="{% if task.completed == 1 %} hidden {% else %} checkbox {% endif %}" id="checkbox-{{ task.id }}" 
                            name="checkbox-accordion"
                        />
                        <label class="list-label" for="checkbox-{{ task.id }}">
                            <input type="checkbox"  {% if task.completed == 1 %} CHECKED {% endif %} />
                            {{ task.title }}
                            <i class="fa fa-angle-down"></i>
                            <!-- <i class="fa fa-angle-up"></i> -->
                        </label>
                        <div class="content">
                            <form>
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label for="inputEmail4">Notes</label>
                                        <textarea name="content" class="form-control" rows="5">{{ request.form['content'] or task.content }}</textarea>
                                    </div>
                                    <div class="form-row col-md-6">
                                        <div class="form-group col-md-12">
                                            <label for="inputState">Priority</label>
                                            <select name="priority" id="inputState" class="form-control">
                                                <option {% if task.priority == 'HIGH' %} SELECTED {% endif %} value="HIGH">
                                                    High
                                                </option>
                                                <option {% if task.priority == 'LOW' %} SELECTED {% endif %} value="LOW">
                                                    Low
                                                </option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <!-- <button type="submit" class="btn btn-danger" style="float:right">Delete</button> -->
                            </form>
                            <form action="{{ url_for('auth.deleteTask', id=task.id) }}" method="POST">
                                <input type="hidden" name="grpName" value="{{ request.path.split('/')[-1] }}" />
                                <input type="submit" value="Delete"
                                        class="btn btn-danger btn-sm"
                                        onclick="return confirm('Are you sure you want to delete this task?')">
                            </form>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% endblock content%}